
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.SceneManagement;

public class Chest_generator : MonoBehaviour
{
    /*ï¿½ó” ‚ï¿½éŒ¾*/
    public GameObject Prefab_open_chest;
    public GameObject first_chest;
    public GameObject first_chest1;
    public GameObject first_chest2;
    public GameObject first_chest3;
    public GameObject first_chest4;
    public GameObject first_chest5;
   

    /*ï¿½Jï¿½Ú‚ï¿½ï¿½ï¿½pï¿½lï¿½ï¿½ï¿½ï¿½éŒ¾*/
    public GameObject GetTreasure_Panel;
    public GameObject Name_Object = null;

    public GameObject TreasureList_Panel;
    
 
    /*ï¿½ó” ‚ï¿½ï¿½Jï¿½ï¿½ï¿½ï¿½ï¿½Æ‚ï¿½ï¿½ï¿½SEï¿½ï¿½éŒ¾*/
    public AudioClip chest_open_SE;
    AudioSource aud;
    //int Tap_num = 0;

    /*ï¿½ó•¨‚ï¿½éŒ¾*/
    public GameObject Burger_prefab;
    public GameObject Croissant_prefab;
    public GameObject Pineapple_prefab;
    public GameObject Pizza_prefab;
    public GameObject Sushi_prefab;
    public GameObject Watermelon_prefab;

    /*ï¿½Ç‰ï¿½*/
    public GameObject t1Button;
    public GameObject t2Button;
    public GameObject t3Button;
    public GameObject t4Button;
    public GameObject t5Button;
    public GameObject t6Button;
    public GameObject GametoListButton;

    public Sprite BurgerImg;
    public Sprite CroissantImg;
    public Sprite PineappleImg;
    public Sprite PizzaImg;
    public Sprite SushiImg;
    public Sprite WatermelonImg;


    //ï¿½@ï¿½^ï¿½ï¿½ï¿½@ï¿½@ ï¿½zï¿½ï¿½Ì–ï¿½ï¿½O ï¿½Ç‰ï¿½
    GameObject[] TreasureBox;
    GameObject[] ChestBox;
    int[] TapBox;
    string[] NameBox;

    Sprite[] ImgBox;
    GameObject[] ButtonBox;



    int id = 0;
    int tre_id;
    Vector3 Chest_Pos;
    Vector3 Tre_Pos;


    void Start()
    {
        /*ï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½*/
        this.aud = GetComponent<AudioSource>();

        /*ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½×‚ï¿½ï¿½Å‚È‚ï¿½ï¿½pï¿½lï¿½ï¿½ï¿½ï¿½ï¿½\ï¿½ï¿½*/
        GetTreasure_Panel.SetActive(false);
        TreasureList_Panel.SetActive(false);

        // ï¿½zï¿½ï¿½Ì–ï¿½ï¿½Oï¿½@ï¿½@ï¿½@ï¿½@ï¿½^ï¿½ï¿½ï¿½@ï¿½@ï¿½@ï¿½@ï¿½@ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Qï¿½[ï¿½ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½g ï¿½Ç‰ï¿½
        TreasureBox = new GameObject[] { Burger_prefab, Croissant_prefab, Pineapple_prefab, Pizza_prefab, Sushi_prefab, Watermelon_prefab };

        ChestBox = new GameObject[] { first_chest, first_chest1, first_chest2, first_chest3, first_chest4, first_chest5 };

        TapBox = new int[] { 0, 0, 0, 0, 0, 0 };

        NameBox = new string[]{ "ãƒãƒ³ãƒãƒ¼ã‚¬ãƒ¼", "ã‚¯ãƒ­ãƒ¯ãƒƒã‚µãƒ³", "ãƒ‘ã‚¤ãƒŠãƒƒãƒ—ãƒ«", "ãƒ”ã‚¶", "å¯¿å¸", "ã‚¹ã‚¤ã‚«" };

        ImgBox = new Sprite[] { BurgerImg, CroissantImg, PineappleImg, PizzaImg, SushiImg, WatermelonImg };

        ButtonBox = new GameObject[] { t1Button, t2Button, t3Button, t4Button, t5Button, t6Button };

    }

    void Update()
    {
        if (Input.GetMouseButtonDown(0))
        {
            Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
            id = 0;

            if (Physics.Raycast(ray, out RaycastHit hit))
            {
                foreach (GameObject g in ChestBox)
                {
                    id += 1;
                    if (hit.transform.name == g.name)
                    {
                        id -= 1;

                        Chest_Pos = new Vector3(g.transform.position.x, g.transform.position.y, g.transform.position.z);
                        Tre_Pos = new Vector3(g.transform.position.x, g.transform.position.y + 0.3f, g.transform.position.z - 0.1f);
                        //Debug.Log(Chest_Pos);//ï¿½Â‚ï¿½ï¿½ï¿½ï¿½ó” ‚ÌˆÊ’uï¿½ï¿½ï¿½æ“¾
                        Instantiate(Prefab_open_chest, Chest_Pos, Quaternion.Euler(-90f, 0.0f, -90f));
                        //ï¿½Â‚ï¿½ï¿½ï¿½ï¿½ó” ‚ÌˆÊ’uï¿½ÉŠJï¿½ï¿½ï¿½ï¿½ï¿½ó” ‚ğ¶ï¿½ï¿½ï¿½ï¿½ï¿½
                        
                        this.aud.PlayOneShot(this.chest_open_SE);
                        
                        ChestBox[id].SetActive(false);
                        TapBox[id] += 1;
                        

                        tre_id = id;
                        //Debug.Log(tre_id);
                        Invoke(nameof(GetShowMethod), 0.8f);

                    }
                }
            }
        }
    }
    

    void GetShowMethod()
    {
        GetTreasure_Panel.SetActive(true);//ï¿½ó•¨‚ï¿½ï¿½Qï¿½bï¿½gï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ê‚ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
        GametoListButton.SetActive(false);
        Instantiate(TreasureBox[tre_id], Tre_Pos, Quaternion.identity);
        //Debug.Log(tre_id);
        Text Name_Text = Name_Object.GetComponent<Text>();
        Name_Text.text = "å®ç‰©: " + NameBox[tre_id];
        ButtonBox[tre_id].GetComponent<Image>().sprite = ImgBox[tre_id];

    }

    public void ToListButtonDown()
    {
        //Debug.Log("ï¿½{ï¿½^ï¿½ï¿½1ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½");
        GetTreasure_Panel.SetActive(false);
        TreasureList_Panel.SetActive(true);
        
        //ShowListMethod();
    }
    
    public void ToBackButton_gDown()
    {
        //Debug.Log("ï¿½{ï¿½^ï¿½ï¿½2ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½");
        GetTreasure_Panel.SetActive(false);
        GametoListButton.SetActive(true);
    }

    public void ToBackButton_tDown()
    {
        //Debug.Log("ï¿½{ï¿½^ï¿½ï¿½3ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½");
        TreasureList_Panel.SetActive(false);
        GametoListButton.SetActive(true);

    }

    public void GametoListBottonDown()
    {
        //Debug.Log("ï¿½{ï¿½^ï¿½ï¿½4ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½"); 
        TreasureList_Panel.SetActive(true);
        GametoListButton.SetActive(false);
    }
}

/*
 ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
    //open_chestï¿½ï¿½ï¿½Aï¿½Nï¿½eï¿½Bï¿½uï¿½É‚ï¿½ï¿½ï¿½ï¿½ó” ‚Ì‘Oï¿½É’uï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
    //getPanelï¿½ï¿½\ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Æ•ó•¨‚ï¿½ó” ‚Ì‘Oï¿½É’uï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
ï¿½@ï¿½@//getï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½Wï¿½ï¿½ï¿½[ï¿½ï¿½Treasureï¿½ï¿½ï¿½Xï¿½gï¿½pï¿½lï¿½ï¿½ï¿½É•\ï¿½ï¿½ï¿½Å‚ï¿½ï¿½ï¿½æ‚¤ï¿½É‚ï¿½ï¿½ï¿½
 */